//@version=4
strategy(title="VWMA 1hr", shorttitle="VWMA1HR",
     calc_on_order_fills=false, initial_capital=100, default_qty_value=100, process_orders_on_close=true,
     default_qty_type=strategy.cash, calc_on_every_tick=true, pyramiding=0,
     currency=currency.USD, commission_type=strategy.commission.percent,
     commission_value=0.1, overlay=true)

fromMonth = input(5)
fromDay = input(20)
thruMonth = input(5)
thruDay = input(25)
fromYear = input(2021)
thruYear = input(2021)
testPeriodStart = timestamp(fromYear, fromMonth, fromDay, 0, 0)
testPeriodStop  = timestamp(thruYear, thruMonth, thruDay, 0, 0)
start           = timestamp(fromYear, fromMonth, fromDay, 13, 00)
finish          = timestamp(thruYear, thruMonth, thruDay, 23, 59)
window() => time >= start and time <= finish ? true : false

//////////////////////////////////////////////////////////////////////////////////
n = input(title="Periods", defval=2, minval=2, type=input.integer)


// UpFractal
bool upflagDownFrontier = true
bool upflagUpFrontier0 = true
bool upflagUpFrontier1 = true
bool upflagUpFrontier2 = true
bool upflagUpFrontier3 = true
bool upflagUpFrontier4 = true

for i = 1 to n
    upflagDownFrontier := upflagDownFrontier and (high[n-i] < high[n])
    upflagUpFrontier0 := upflagUpFrontier0 and (high[n+i] < high[n])
    upflagUpFrontier1 := upflagUpFrontier1 and (high[n+1] <= high[n] and high[n+i + 1] < high[n])
    upflagUpFrontier2 := upflagUpFrontier2 and (high[n+1] <= high[n] and high[n+2] <= high[n] and high[n+i + 2] < high[n])
    upflagUpFrontier3 := upflagUpFrontier3 and (high[n+1] <= high[n] and high[n+2] <= high[n] and high[n+3] <= high[n] and high[n+i + 3] < high[n])
    upflagUpFrontier4 := upflagUpFrontier4 and (high[n+1] <= high[n] and high[n+2] <= high[n] and high[n+3] <= high[n] and high[n+4] <= high[n] and high[n+i + 4] < high[n])
flagUpFrontier = upflagUpFrontier0 or upflagUpFrontier1 or upflagUpFrontier2 or upflagUpFrontier3 or upflagUpFrontier4

upFractal = (upflagDownFrontier and flagUpFrontier)


// downFractal
bool downflagDownFrontier = true
bool downflagUpFrontier0 = true
bool downflagUpFrontier1 = true
bool downflagUpFrontier2 = true
bool downflagUpFrontier3 = true
bool downflagUpFrontier4 = true

for i = 1 to n
    downflagDownFrontier := downflagDownFrontier and (low[n-i] > low[n])
    downflagUpFrontier0 := downflagUpFrontier0 and (low[n+i] > low[n])
    downflagUpFrontier1 := downflagUpFrontier1 and (low[n+1] >= low[n] and low[n+i + 1] > low[n])
    downflagUpFrontier2 := downflagUpFrontier2 and (low[n+1] >= low[n] and low[n+2] >= low[n] and low[n+i + 2] > low[n])
    downflagUpFrontier3 := downflagUpFrontier3 and (low[n+1] >= low[n] and low[n+2] >= low[n] and low[n+3] >= low[n] and low[n+i + 3] > low[n])
    downflagUpFrontier4 := downflagUpFrontier4 and (low[n+1] >= low[n] and low[n+2] >= low[n] and low[n+3] >= low[n] and low[n+4] >= low[n] and low[n+i + 4] > low[n])
flagDownFrontier = downflagUpFrontier0 or downflagUpFrontier1 or downflagUpFrontier2 or downflagUpFrontier3 or downflagUpFrontier4

downFractal = (downflagDownFrontier and flagDownFrontier)
//////////////////////////////////////////////////////////////////////////////////////////////////////////

len = 24
src = security(syminfo.tickerid, "60", hlc3, barmerge.gaps_off, lookahead=barmerge.lookahead_off)
ma = vwma(src, len)
plot(ma, title="VWMA", color=color.blue)
upperBandValue = input(3.5, title = "Short Offset")
lowerBandValue = input(3.5, title= "Long Offset")
upperBand = plot(ma*(1+upperBandValue/100), title="Upper Band", color=color.red)
lowerBand = plot(ma*(1-lowerBandValue/100), title="Lower Band", color=color.green)

doo = ma*(1+upperBandValue/100)
if close > doo and downFractal
    strategy.entry("Short", strategy.long, when=window())

if strategy.position_avg_price > close and abs((strategy.position_avg_price-close) / close) >= 0.05
    strategy.close_all(when=window())
