study(title="uabmacd",shorttitle="uabmacd")
//strategy(title="uabmacd",shorttitle="uabmacd",initial_capital=100,currency=currency.USD,default_qty_type=strategy.percent_of_equity,default_qty_value=100)


// MACD
// ===
// Getting inputs
fast_length = input(title="Fast Length", type=integer, defval=10)
slow_length = input(title="Slow Length", type=integer, defval=20)
src = input(title="Source", type=source, defval=close)
signal_length = input(title="Signal Smoothing", type=integer, minval = 1, maxval = 50, defval = 6)
sma_source = input(title="Simple MA (Oscillator)", type=bool, defval=false)
sma_signal = input(title="Simple MA (Signal Line)", type=bool, defval=false)

// Calculating
fast_ma = sma_source ? sma(src, fast_length) : ema(src, fast_length)
slow_ma = sma_source ? sma(src, slow_length) : ema(src, slow_length)
macd = fast_ma - slow_ma
signal = sma_signal ? sma(macd, signal_length) : ema(macd, signal_length)
hist = macd - signal
//==============================================================================================

// WaveTrend
// =========
n1 = input(10, "Channel Length")
n2 = input(21, "Average Length")
obLevel1 = input(60, "Over Bought Level 1")
obLevel2 = input(53, "Over Bought Level 2")
osLevel1 = input(-60, "Over Sold Level 1")
osLevel2 = input(-53, "Over Sold Level 2")

ap = hlc3
esa = ema(ap, n1)
d = ema(abs(ap - esa), n1)
ci = (ap - esa) / (0.015 * d)
tci = ema(ci, n2)

wt1 = tci
wt2 = sma(wt1,4)

plot(0, color=gray)
plot(obLevel1, color=red)
plot(osLevel1, color=green)
plot(obLevel2, color=red)
plot(osLevel2, color=green)

plot(wt1, color=green)
plot(wt2, color=red)
plot(wt1-wt2, color=blue, style=area, transp=80)

plot(cross(wt1, wt2) ? wt2 : na, color = black , style = circles, linewidth = 3)
plot(cross(wt1, wt2) ? wt2 : na, color = (wt2 - wt1 > 0 ? red : lime) , style = circles, linewidth = 2)

barcolor(cross(wt1, wt2) ? (wt2 - wt1 > 0 ? aqua : yellow) : na)

// --------------------------------------------------
wt1_past = wt1[1]
wt2_past = wt2[1]

divlong = wt1 > wt2 and wt1_past < wt2_past and wt1_past < osLevel2
divshort = wt1 < wt2 and wt1_past > wt2_past and wt1_past > obLevel2

data1 = divlong
plotshape(data1, style=shape.xcross,location=location.bottom, color=green, size = size.tiny, title="WT_up")

data2 = divshort
plotshape(data2, style=shape.xcross,location=location.top, color=red, size = size.tiny, title="WT_down")
plotshape(data1 or data2, style=shape.xcross,location=location.absolute, color=gray, title="WT_BOTH")
plot(cross(wt1, wt2) ? wt2 : na, color = black , style = circles, linewidth = 3)
plot(cross(wt1, wt2) ? wt2 : na, color = (wt2 - wt1 > 0 ? red : lime) , style = circles, linewidth = 2)

fromYear = input(2020, "Backtest Start Year")
fromMonth = input(1, "Backtest Start Month")
fromDay = input(2, "Backtest Start Day")
testPeriodStart = timestamp(fromYear,fromMonth,fromDay,0,0)

thruYear = input(2021, "Backtest Stop Year")
thruMonth = input(12, "Backtest Stop Month")
thruDay = input(30, "Backtest Stop Day")
testPeriodStop = timestamp(thruYear,thruMonth,thruDay,0,0)

start     = timestamp(fromYear, fromMonth, fromDay, 00, 00)  // backtest start window
finish    = timestamp(thruYear, thruMonth, thruDay, 23, 59)  // backtest finish window
window()  => time >= start and time <= finish ? true : false

divcrosslong  = wt1 - wt2 < 0
divcrossshort = wt1 - wt2 > 0

_divcrosslong  = wt1 < wt2 and wt1_past > wt2_past
_divcrossshort = wt1 > wt2 and wt1_past < wt2_past

hist_long = hist > 0
hist_short = hist < 0

alertcondition(_divcrossshort, title='DOGEUSDT,LONG',  message='DOGEUSDT,LONG')
alertcondition(_divcrosslong,  title='DOGEUSDT,SHORT', message='DOGEUSDT,SHORT')
//
//alertcondition(divcrossshort, title='DOGE,SHORT,OPEN', message='Div Long')
//alertcondition(divcrosslong, title='DOGE,SHORT,CLOSE', message='Div Long')


//strategy.entry("Long", strategy.long, when=window() and _divcrossshort)
//strategy.close("Long", when=window() and _divcrosslong)
//strategy.entry("Short",strategy.short, when=window() and _divcrosslong)
//strategy.close("Short", when=window() and _divcrossshort)

//-----------------------------------------------------------------------------------
//strategy.entry("Long", strategy.long, when=window() and divcrossshort and hist_long)
//strategy.close("Long", when=window() and divcrosslong and hist_short)

//strategy.entry("Short",strategy.short, when=window() and divcrosslong and hist_short)
//strategy.close("Short", when=window() and divcrossshort and hist_long)
