* Experiences and Ideas
1. Higher than 3x is very high risk with large amount of money. You won’t
   realize how big would be the loss.
2. Case lets say you have long position and you close it by short on the right
   side, in some cases when you close the position it may re-open as short just
   be careful; you think you close the position and get your gain but it may
   opened a reverse position may put you in reverse case and bring loss; if you
   have large money the lost will be much more
3. If you are scared of the position just put close on top of the entry price
   before, do not think any gain
4. Stop at 5% doing cut-loss
5. When you put extra money like 500$ just be careful do not lose control
6. Close position if BTC is dropping and you are long (if you are in gain), do
   not wnat more and close the position otherwise you will be rekt
7. Do not trade in the morning of a big loss >100$ on the next day
8. Do not play with more than your boundaries
9. Do not trade if you get modafil at midnight
10. Do not trade while watching youtube video
11. If you are in loss and entered with a large amount of money put a stop-loss
    to `entry price` and sell it when it hits to `entry price`.
12. Do not open multiple positions its hard to keep track of and will let you
    make stupid mistakes at the end of the day.
13. Check before start trading does `trbinance.com` works, like is it in
    maintenance, can you tranfer money?
14. BTC USDT’e cevirince bir anda gomme parca parca gom. Ucuz fiyattan
    mermilerini feda edersin acele etme cikacagi kadar ciksin durulsun, tepede
    gomersin. Erkenden fazla para gomersen onu da maliyeti yukari cekip
    kurtarmak bi o kadar zor olur
15. Short/Long sinyali gelince BTC leri kullan kadana gore pump olurken harcama,
    yuksek fiyata koy. Mesela shorttayken yesilde al olursa ucuza gidebilir.
16. 5 dakikalikta pozisyon ne ise tersini yapma, tehlikeli
17. Funding rate’e bak
18. Isleme girmeden ne kadar paran var bosta ne nerde listesini cikar
19. Profit from Binance Funding: https://www.youtube.com/watch?v=DoibtunxbsI
20. https://coinalyze.net/waves/usdt/binance/liquidation-chart/wavesusdt_perp_lq/
