//
// @author alper
//
//@version=4
strategy(title="{{ticker}},{{strategy.order.action}},{{strategy.order.alert_message}},{{close}},",
     shorttitle="alpy_spot",
     calc_on_order_fills=true, initial_capital=750, default_qty_value=7,
     process_orders_on_close=false, default_qty_type=strategy.cash,
     calc_on_every_tick=true, pyramiding=100000,
     currency=currency.USD, commission_type=strategy.commission.percent,
     commission_value=0.1, overlay=false)

upperBandValue = input(3.0, title = "Short Offset")
lowerBandValue = input(3.0, title = "Long Offset")
//
fromMonth = 6
fromDay   = 1
thruMonth = 12
thruDay   = 30
fromYear  = 2021
thruYear  = 2021
testPeriodStart = timestamp(fromYear, fromMonth, fromDay, 0, 0)
testPeriodStop  = timestamp(thruYear, thruMonth, thruDay, 0, 0)
start           = timestamp(fromYear, fromMonth, fromDay, 13, 00)
finish          = timestamp(thruYear, thruMonth, thruDay, 23, 59)
window() => time >= start and time <= finish ? true : false
is_long  = strategy.position_size > 0
is_short = strategy.position_size < 0
_timenow = timenow / 1000
n = 2 // williams_fractial
SLEEP_SECONDS = 75
src = hlc3

    // VWMA
// ====
len = 24
_src = security(syminfo.tickerid, "60", hlc3)
ma = vwma(_src, len)
plot(ma, title="VWMA", color=color.blue)
upperBand = plot(ma * (1 + upperBandValue / 100), title="Upper Band", color=color.red)
lowerBand = plot(ma * (1 - lowerBandValue / 100), title="Lower Band", color=color.green)


n1 = 10  //Channel Length
n2 = 21  //Average Length
obLevel1 = 60   // Over Bought Level 1
obLevel2 = 53   // Over Bought Level 2
osLevel1 = -60  // Over Sold Level 1
osLevel2 = -53  // Over Sold Level 2

esa = ema(src, n1)
d = ema(abs(src - esa), n1)
ci = (src - esa) / (0.015 * d)
tci = ema(ci, n2)
wt1 = tci  // green-line
wt2 = sma(wt1, 4)  // red-line

plot(obLevel1, color=color.red)
plot(osLevel1, color=color.green)
plot(obLevel2, color=color.red, style=3)
plot(osLevel2, color=color.green, style=3)
plot(wt1, color=color.green)
plot(wt2, color=color.red)
plot(wt1-wt2, color=color.new(color.blue, 70), style=plot.style_area)

plot(cross(wt1, wt2) ? wt2 : na, color=color.black , style=plot.style_circles, linewidth=3)
plot(cross(wt1, wt2) ? wt2 : na, color = (wt2 > wt1 ? color.red : color.lime) , style=plot.style_circles, linewidth=2)
barcolor(cross(wt1, wt2) ? (wt2 - wt1 > 0 ? color.aqua : color.yellow) : na)
plot(cross(wt1, wt2) ? wt2 : na, color = (wt2 - wt1 > 0 ? color.red : color.lime) , style=plot.style_circles, linewidth = 2)

val = abs(wt1 - wt2)
OS_LEVEL = 0  // -75
buy_signal  = wt1 > wt2 and wt1[1] < wt2[1] and wt2[1] < OS_LEVEL
sell_signal = wt1 < wt2 and wt1[1] > wt2[1]  // and close > 0.015
//plot(val, "val", color.black)

if buy_signal
    if strategy.opentrades[0] == 0 or is_short
        strategy.entry("Long", strategy.long, when=window(), alert_message="enter_1D")

if sell_signal
    if strategy.opentrades[0] == 0 or is_long
        strategy.close_all(when=window())

if strategy.position_size[0] != 0 and strategy.position_avg_price > close and close <= strategy.position_avg_price * 0.99
    strategy.close_all(when=window())  // Close all Long
