//
// @author alper
//
//@version=4
strategy(title="vwma", overlay=true)
upperBandValue = input(3.0, title = "Short Offset")
lowerBandValue = input(3.0, title = "Long Offset")
len = 24
src = hlc3
ma = vwma(src, len)
plot(ma, title="VWMA", color=color.blue)
upperBand = plot(ma * (1 + upperBandValue / 100), title="Upper Band", color=color.red)
lowerBand = plot(ma * (1 - lowerBandValue / 100), title="Lower Band", color=color.green)
