//Created by ChrisMoody on 11-18-2014
//Designed to Go with ADX Trading System.
//@version=4
study(title="CM_DI_Plus_Minus_V1", shorttitle="CM_DI_Plus_Minus_V1")
len = input(14, minval=1, title="DI Length")
lensig = input(14, title="ADX Smoothing", minval=1, maxval=50)
sbh = input(true, title="Show BackGround Highlight")
up = change(high)
down = -change(low)
trur = rma(tr, len)
plus = fixnan(100 * rma(up > down and up > 0 ? up : 0, len) / trur)
minus = fixnan(100 * rma(down > up and down > 0 ? down : 0, len) / trur)
sum = plus + minus
adx = 100 * rma(abs(plus - minus) / (sum == 0 ? 1 : sum), lensig)
bgcolor(sbh and plus > minus ? color.lime : sbh and plus < minus ? color.red : na, transp=70)
plot(plus, color=color.lime, title="+DI", style=plot.style_linebr, linewidth=3)
plot(minus, color=color.red, title="-DI", style=plot.style_linebr, linewidth=3)
