//@version=4
strategy(title="{{ticker}},{{strategy.order.action}},{{strategy.order.alert_message}},{{close}},",
     shorttitle="alpy_vix",
     calc_on_order_fills=true,
     process_orders_on_close=true,
     default_qty_type=strategy.cash,
     calc_on_every_tick=true,
     overlay=false,
     pyramiding=100000)

fromMonth = 10
fromDay = 1
thruMonth = 1
thruDay = 1
thruYear = 3000
fromYear = 2023

shortest = ema(close, 20)
short = ema(close, 50)
longer = ema(close, 100)
longest = ema(close, 200)
// ema_max = math.max(math.max(math.max(shortest,short), longer), longest)
ema_max = max(shortest,short, longer, longest)

testPeriodStart = timestamp(fromYear, fromMonth, fromDay, 0, 0)
testPeriodStop = timestamp(thruYear, thruMonth, thruDay, 0, 0)
start = timestamp(fromYear, fromMonth, fromDay, 13, 00)
finish = timestamp(thruYear, thruMonth, thruDay, 23, 59)
msg = timeframe.period + "_enter"
msg_aggr = msg + "_aggr"
window() =>
    time >= start and time <= finish ? true : false

// 30m @BTCUSDT binance-usdt , once-per-minitue, https://alpybot.duckdns.org/webhook
// __ https://www.tradingview.com/script/2KE8wTuF-Indicator-WaveTrend-Oscillator-WT
n1 = 10 //Channel Length
n2 = 21 //Average Length
obLevel1 = 60 // over bought Level 1
obLevel2 = 53 // over bought Level 2
osLevel2 = -53 // over sold Level 2
osLevel1 = -60 // over sold Level 1
// wave_trend_time = input("60", title = "WaveTrend Time")
// src = security(syminfo.tickerid, wave_trend_time, hlc3)
src = hlc3
esa = ema(src, n1)
d = ema(abs(src - esa), n1)
ci = (src - esa) / (0.015 * d)
tci = ema(ci, n2)
wt1 = tci // green-line
wt2 = sma(wt1, 4) // red-line
plot(obLevel1, color=color.red)
plot(osLevel1, color=color.green)
plot(obLevel2, color=color.red, style=3)
plot(osLevel2, color=color.green, style=3)
plot(wt1, color=color.green)
plot(wt2, color=color.red)
plot(wt1-wt2, color=color.new(color.blue, 70), style=plot.style_area)
plot(cross(wt1, wt2) ? wt2 : na, color=color.black , style=plot.style_circles, linewidth=3)
plot(cross(wt1, wt2) ? wt2 : na, color = (wt2 > wt1 ? color.red : color.lime) , style=plot.style_circles, linewidth=2)
plot(cross(wt1, wt2) ? wt2 : na, color = (wt2 - wt1 > 0 ? color.red : color.lime) , style=plot.style_circles, linewidth=2)
// alertcondition(condition=wt1 >= wt2 and wt1 < -50 , title="green_WaveTrend", message="green")
// alertcondition(condition=wt2 > wt1, title="red_WaveTrend", message="red")

wt1_past_1 = wt1[1]
wt2_past_1 = wt2[1]
divcrosslong = wt1 < wt2
divcrossshort = wt1 > wt2
_divcrosslong = divcrosslong and wt1_past_1 > wt2_past_1
_divcrossshort = divcrossshort and wt1_past_1 < wt2_past_1

is_div_long = wt1 > wt2 and wt1_past_1 < wt2_past_1 and wt1 <= 0
is_div_short = wt1 < wt2 and wt1_past_1 > wt2_past_1 and wt2 >= 0

if window()
    if is_div_long and wt1 < -55
        strategy.entry("c", strategy.long, qty=1, alert_message="")
    if is_div_short and wt1 > 55
        strategy.entry("s", strategy.short, qty=1, alert_message="")
