root:
  fast: true
  is_balance_silent: true
  isolated_wallet_limit: 150
  discord_msg_above_usdt: 150
  take_profit: 0.0047
  locked_percent_limit: 99
  is_write: false
  is_funding_rate_alert: false
  ignore: # for all
    - DUMMY
    # - OG
  ignore_warning:
    - BOND
    - DUMMY
  # ignore_position_log:
  #   - OAX
  usdt:
    status: off   # "on" or "off"
    is_manual_trade: false
    auto_buy_bnb: on
    isolated: off
    cross: off
    max_pos: 2
    initial: 11
    multiply_ratio: 1.13
    percent_change_to_add: 4.5
    stop_trade_wt_30m_red: false
    entry_prices:
      DUMMY: 1.0
    change_type:  # to btc
      - DUMMY
    alert_if_position_closed: []  # OAX
  btc:
    status: on
    is_manual_trade: false
    auto_buy_bnb: on
    isolated: off
    cross: off
    initial: 0.00011
    max_pos: 10
    multiply_ratio: 1.13
    percent_change_to_add: 4
    stop_trade_wt_30m_red: false
    entry_prices:
      DUMMY: 1.0
    # change_type:  # to usdt
    #   - OG
    ignore:
      - DUMMY
    alert_if_position_closed:
      - DUMMY
