files:
  input: pairs.csv
tradingview:
  chartUrl: https://www.tradingview.com/chart/wWjs7nTb/?symbol=BITSTAMP%3ABTCUSD
  interval: 1m  # examples: 1s | 30s | 1m | 15m | 1h | 1D | 1M
alert:
  condition:
    primaryLeft: alpy_vix
  actions:
    notifyOnApp: false
    showPopup: false
    sendEmail: false
    webhook:
      enabled: true
      url: "https://alpyr-bot.duckdns.org/webhook"
message: >
  {   {{ticker}},
      {{strategy.order.action}},
      {{strategy.order.alert_message}},
      {{close}},
      {{strategy.position_size}},
      {{strategy.prev_market_position}},
      {{strategy.prev_market_position_size}},
  }
