files:
  input: pairs_usdt.csv
tradingview:
  chartUrl: https://www.tradingview.com/chart/bHXZrXAy/?symbol=BINANCE%3ABTCUSDT
  interval: 5m
alert:
  condition:
    primaryLeft: alpy_vix
    primaryRight:
  actions:
    notifyOnApp: false
    showPopup: false
    sendEmail: false
    webhook:
      enabled: true
      url: "https://alpybot.duckdns.org/webhook"
  message: >
    {{ticker}},{{strategy.order.action}},{{strategy.order.alert_message}},{{close}},{{strategy.position_size}},{{time}},
