// This source code is subject to the terms of the Mozilla Public License 2.0 at
// https://mozilla.org/MPL/2.0/ © lavventura
strategy(title="WaveTrend with Crosses [LazyBear]",
                        shorttitle="WT_CROSS",
                        process_orders_on_close=true,
                        initial_capital=1000,
                        currency=currency.USD,
                        default_qty_value=10
                        default_qty_type=strategy.percent_of_equity,
                        // calc_on_every_tick=true
                        )

// https://kodify.net/tradingview/strategy-settings/process-orders-close/#toggle-strategy-orders-on-close-in-tradingview

//==============================================================================================
// MACD
// ===
// Getting inputs
fast_length = input(title="Fast Length", type=integer, defval=10)
slow_length = input(title="Slow Length", type=integer, defval=20)
src = input(title="Source", type=source, defval=close)
signal_length = input(title="Signal Smoothing", type=integer, minval = 1, maxval = 50, defval = 5)
sma_source = input(title="Simple MA (Oscillator)", type=bool, defval=false)
sma_signal = input(title="Simple MA (Signal Line)", type=bool, defval=false)

// Calculating
fast_ma = sma_source ? sma(src, fast_length) : ema(src, fast_length)
slow_ma = sma_source ? sma(src, slow_length) : ema(src, slow_length)
macd = fast_ma - slow_ma
signal = sma_signal ? sma(macd, signal_length) : ema(macd, signal_length)
hist = macd - signal
//==============================================================================================

// WaveTrend
// =========
n1 = input(10, "Channel Length")
n2 = input(21, "Average Length")
obLevel1 = input(60, "Over Bought Level 1")
obLevel2 = input(53, "Over Bought Level 2")
osLevel1 = input(-60, "Over Sold Level 1")
osLevel2 = input(-53, "Over Sold Level 2")

ap = hlc3
esa = ema(ap, n1)
d = ema(abs(ap - esa), n1)
ci = (ap - esa) / (0.015 * d)
tci = ema(ci, n2)

wt1 = tci
wt2 = sma(wt1,4)

plot(0, color=gray)
plot(obLevel1, color=red)
plot(obLevel2, color=red)
//
plot(osLevel1, color=green)
plot(osLevel2, color=green)

plot(wt1, color=lime)
plot(wt2, color=red)
plot(wt1-wt2, color=blue, style=area, transp=80)

plot(cross(wt1, wt2) ? wt2 : na, color = black , style = circles, linewidth = 3)
plot(cross(wt1, wt2) ? wt2 : na, color = (wt2 - wt1 > 0 ? red : lime) , style = circles, linewidth = 2)
barcolor(cross(wt1, wt2) ? (wt2 - wt1 > 0 ? aqua : yellow) : na)

// --------------------------------------------------
wt1_past = wt1[1]
wt2_past = wt2[1]

divlong = wt1 > wt2 and wt1_past < wt2_past and wt1_past < osLevel2  // over sell and buy
divshort = wt1 < wt2 and wt1_past > wt2_past and wt1_past > obLevel2 // over sell and buy

data1 = divlong
data2 = divshort

plotshape(data1, style=shape.xcross,location=location.bottom, color=lime, size = size.tiny, title="WT_up")
plotshape(data2, style=shape.xcross,location=location.top, color=red, size = size.tiny, title="WT_down")
plot(cross(wt1, wt2) ? wt2 : na, color = black , style = circles, linewidth = 3)
plot(cross(wt1, wt2) ? wt2 : na, color = (wt2 - wt1 > 0 ? red : lime) , style = circles, linewidth = 2)
plotchar(data1 or data2, char="",title="WT_BOTH")  // in order to show it on the Alert section

fromYear = input(2020, "Backtest Start Year")
fromMonth = input(1, "Backtest Start Month")
fromDay = input(2, "Backtest Start Day")
testPeriodStart = timestamp(fromYear,fromMonth,fromDay,0,0)

thruYear = input(2021, "Backtest Stop Year")
thruMonth = input(12, "Backtest Stop Month")
thruDay = input(30, "Backtest Stop Day")
testPeriodStop = timestamp(thruYear,thruMonth,thruDay,0,0)

start     = timestamp(fromYear, fromMonth, fromDay, 00, 00)  // backtest start window
finish    = timestamp(thruYear, thruMonth, thruDay, 23, 59)  // backtest finish window
window()  => time >= start and time <= finish ? true : false

divcrossshort = wt1 - wt2 < 0
divcrosslong = wt1 - wt2 > 0

hist_long = hist > 0
hist_short = hist < 0

strategy.entry("Long", strategy.long, when=window() and divcrosslong and hist_long)
strategy.close("Long", when=window() and divcrossshort and hist_short)

strategy.entry("Short",strategy.short, when=window() and divcrossshort and hist_short)
strategy.close("Short", when=window() and divcrosslong and hist_long)
// 38/14/10 == slow/fast/signal_length
