setup:
  IGNORE_BELOW_USDT: 0.01
  ISOLATED_WALLET_LIMIT: 100
  STOP_LOCKED_PER: 50
  TP: 0.0051
  ignore:
    spot:
    - PAIR
    usdtperp:
    - PAIR
  spot:
    INITIAL_BTC_QTY: 0.00015
    LOCKED_PERCENT_LIMIT: 95
    TP: 0.0051
    max_pos: 1
    max_pos_1m: 1
    multiply_ratio: 1.0
    percent_change_to_add: 5.0
  usdt:
    LOCKED_PERCENT_LIMIT: 95
    TP: 0.0051
    max_pos: 1
    multiply_ratio: 1.2
    percent_change_to_add: 6.0
    pos:
      1s: 20
      1s_sell: 20
  usdtperp:
    locked_percent_limit: 5
    max_pos: 2
    max_pos_1m: 2
    multiply_ratio: 1.7
    percent_change_to_add: 7.0
    pos:
      long:
        1m: 13.0
        base: 12.0
      short:
        1m: 13.0
        base: 12.0
