TRBINANCE:
  USDT: 0.0
portfolio:
  BTC: 0.0
  SILVER:
    gr: 0.0
  TRY: 0.0
  USDT: 0.0
  _TOTAL: 2428.06
position:
  long:
    1m: 100.0
    base: 30.0
  short:
    1m: 100.0
    base: 30.0
setup:
  IGNORE_BELOW_USDT: 0.1
  IGNORE_LIST_FUTURES:
  - PAIR
  IGNORE_LIST_SPOT:
  - PAIR
  INITIAL_BTC_QTY: 0.00015
  INITIAL_LEVERAGE: 1
  LOCKED_PERCENT_LIMIT_SPOT: 10
  LOCKED_PERCENT_LIMIT_USDT: 10
  PERCENT_CHANGE_TO_ADD_SPOT: -5.0
  PERCENT_CHANGE_TO_ADD_USDT: -5.0
  SPOT_MAX_POSITION_NUMBER: 2
  SPOT_MULTIPLY_RATIO: 1.0
  TP: 0.005
  TP_SPOT: 0.005
  USDT_MAX_POSITION_NUMBER: 10
  USDT_MULTIPLY_RATIO: 1.5
z:
  ip: https://alpyr-bot.duckdns.org/webhook
