TRBINANCE:
  USDT: 0.0
portfolio:
  BTC: 0.0
  SILVER:
    gr: 0.0
  TRY: 0.0
  USDT: 0.0
  _TOTAL: 2428.06
position:
  long:
    1m: 50.0
    base: 25.0
  short:
    1m: 50.0
    base: 25.0
setup:
  IGNORE_BELOW_USDT: 0.01
  IGNORE_LIST_FUTURES:
  - PAIR
  INITIAL_LEVERAGE: 1
  ISOLATED_WALLET_LIMIT: {}
  LOCKED_PERCENT_LIMIT_USDT: 5
  PERCENT_CHANGE_TO_ADD_USDT: -5.0
  TP: 0.0051
  USDT_MAX_POSITION: 3
  USDT_MAX_POSITION_1m: 10
  USDT_MULTIPLY_RATIO: 1.6
  spot:
    IGNORE_LIST:
    - PAIR
    INITIAL_BTC_QTY: 0.00015
    LOCKED_PERCENT_LIMIT: 3
    MAX_POSITION: 2
    MAX_POSITION_1m: 3
    MULTIPLY_RATIO: 1.0
    PERCENT_CHANGE_TO_ADD: -5.0
    TP: 0.0051
z:
  ip: https://alpyr-bot.duckdns.org/webhook
