* NOTES

** a price may drop 10% in one minute
- minimum 20% safe cross-margin is a good way to go
- might be good to catch 10% suddent drops in 1 minute instead of pumps, they may end up suddent jump backs.

** cross-margin 3x
- Aslinda 4 kat, 25% duserse liq oluyorsun ama hesaba para koyunca liq fiyati azaliyor fakat ekledigin para kitleniyor.
- extra islem yapinca, ornegin repay yaparsan, hem liq fiyati artti hem de
toplam yapacagim kar azaldi. Islem sirasinda `repay` yapmak karli degil.

** Always sleep your phone in charge if you have alerts and in lose.

* Funding Rate
The payment rate exchanged between the long and short positions for the next
funding. If the funding rate is positive, longs pay shorts. If negative, shorts
pay longs.

* HEADSUP at cross sell normal intead of repay in some casees just be careful

* cross'da zararina kapatip alttan alirsan kardasin
Ornek: 7k 1650 kapatip 1560 (5%) altindan ayni sekilde alabiliyordum. Bunu
yapmadim 1560' dusunce para 7k den 6k ye dustu onunu yerinde 1k zarar oldu yine.
Yani zarardayken satip alttan alabilirsen (akilli hesap ile), en azindan dususte
etkilenmemis oluyorsun.  Spotta olsa zaten oyle yapardin ayni sekilde
dusunebilirsin. 1k kazanma sansim varken onun yerine altap mini alsatlar ile $50
kaybettim.
