* Guide

** tradingview new account

- at macOS open [[mail.com]] and [[tradingview.comman]] on *brave* and click the link from the mail
  for authentication, DO NOT COPY THE LINK and PASTE TO URL it does not accept payment.

** [[http://alpyr.duckdns.org:81][Nginx setup]]

IP: [[https://alpybot.duckdns.org/webhook]]

- [[https://discord.com/developers/applications]]
- [[https://sandwich.finance]]
- [[https://bigpara.hurriyet.com.tr/borsa/canli-borsa/]]
- [[https://nginxproxymanager.com/setup/#configuration-file]]

First: [[<ip_address>:81/login]]

- [[https://console.cloud.google.com/networking/firewalls][Firewall setup]]

Open port ~443~, ~81~, and ~5000~ in Google Instance, under ~default-allow-http~.

* Enable Port Google-Instance

– Navigation Menu => VPN Network => Firewall => Create Firewall Rule
– Name: ipfs
– Logs: Off
– Type: Ingress
– Priority: 1000
– Targets => All instances in the network
– Source IP ranges: 0.0.0.0/0
– TCP: 5000
– Action: Allow
– default
– Off
– Open instance, Edit, network tags => add ipfs
– sudo service network-manager restart or reboot in case

#+begin_src bash
# sudo firewall-cmd --add-port=5000/tcp --permanent --zone=docker
# sudo firewall-cmd --reload
# sudo firewall-cmd --list-all --zone=docker
sudo systemctl enable ufw && sudo ufw enable
sudo systemctl start firewalld
sudo systemctl enable firewalld
sudo ufw allow 80/tcp
sudo ufw allow 81/tcp
sudo ufw allow 443/tcp
sudo ufw allow 5000/tcp
sudo ufw status verbose
sudo nmap localhost
#+end_src

#+begin_src yaml
admin@example.com  | alper.alimoglu@gmail.com
password: changeme
#+end_src

- First ~alpyr.duckdns.org~ and ~alpybot.duckdns.org~ should have the correct new IP.

*** Details
#+begin_src bash
Domain name: alpyr.duckdns.org     | alpybot.duckdns.org
Scheme: http                       | http
<IP>                               | same_ip
Forward: 81                        | 5000
[X] Block Comman Exploits
[X] Websockets Support

[SAVE
#+end_src

*** SSL
#+begin_src bash
Request new SSLcertificate
[X] HTTP/2 Support
[X] Force SSL
[X] HSTS Enables

[SAVE]
#+end_src,

*** update
#+begin_src bash
./update.sh && ./filter.sh
#+end_src

** nginx full setup instructions

- [[http://IP/webhook][IP_example]]

https://askubuntu.com/a/1046217/660555

- http://www.duckdns.org  // login using github
- https://nginxproxymanager.com/setup/

*** public
#+begin_src bash
curl https://alpybot.duckdns.org
curl -X POST https://alpybot.duckdns.org/webhook -d "DOGEUSDT,buy,S_enter_1.0,0.5447,75454,2022-02-06T18:01:51Z,"
curl -X POST https://alpybot.duckdns.org/webhook -d "DOGEUSDTPERP,buy,enter,1.943,"
#+end_src

*** localhost
#+begin_src bash
curl -v https://alpybot.duckdns.org
curl -v 127.0.0.1:5000
curl -X POST http://127.0.0.1:5000/webhook -d "DOGEUSDT,buy,S_enter_1.0,0.5447,75454,2022-02-06T18:01:51Z,"
#+end_src

** Tradingview alerts some links

1. [[https://liquidation.atsutane.net/calc][Binance Minimum Trading Rules for Futures]]
   ~Balance: 15, PercentBal: 100, Leverage: 1~
2. [[https://github.com/puppeteer/puppeteer][puppeteer google browser]]
3. [[https://maildim.com][fake gmail address generator and inbox]]
4. [[https://temp-sms.org][SMS reciever New Zealand Phone number]]
5. tv__username__last__used => ~roxanroxanroxan_16~
6. yb digital card used: 4 times last used ending: **41
7. ~e2-small~ does the job on google instance

** Git Push:

#+begin_src bash
# https://github.com/newren/git-filter-repo#how-do-i-install-it
git filter-repo --invert-paths --path '.DS_Store' --use-base-name
git remote add origin https://github.com/avatar-lavventura/trade_bot.git
git push --set-upstream origin dev -f
#+end_src

** Timestamp for this request is outside of the recvWindow

- https://github.com/ccxt/ccxt/issues/761#issuecomment-355839537

If your server is running on Linux, just execute this script - it will update system time

#+begin_src bash
sudo date -s "$(wget -qSO- --max-redirect=0 google.com 2>&1 | grep Date: | cut -d' ' -f5-8)Z"
#+end_src

Note, however, that system clock can actually go out of synch pretty quickly, in
less than 15 minutes. So this command has to be run frequently enough, or,
alternatively, it can be substituted for a time-synchronizing daemon like ntpd
that will do it for you.

- https://currentmillis.com
- https://askubuntu.com/a/254846/660555

https://askubuntu.com/a/854880/660555

#+begin_src bash
sudo apt install systemd-timesyncd
sudo timedatectl set-timezone UTC
sudo systemctl restart systemd-timesyncd.service
systemctl status systemd-timesyncd
timedatectl status
#+end_src

** tradingview-alerts setup
#+begin_src bash
npx @alleyway/create-tradingview-alerts-home
cd tradingview-alerts-home
npm install
#+end_src

* Google Instance

– Create with 15 GB boot disk, ~e2-small~ // Ubuntu LTS minimal 1 non-preemptible e2-micro VM instance
– per month in one of the following US regions: ~Oregon: us-west1~, ~Iowa: us-central1~, ~South Carolina:
– us-east1~

** notes
- expired TV: alperalperalper123  // used_card ykb bank virtual card:4525
