* BASIC RISK AND MONEY MANAGEMENT

**The most important rule in investing/trading is to protect your capital at all
cost.**

Protecting your capital is more important than missing an opportunity;
once you lose your capital it's game over but there will always be opportunities
in the market. That's why you must use a stop loss (sell stop order) on every
trade.

** 1% Risk Rule Definition:
This could also be the 2%, 3%, 4% or 5% risk rule. The 1% risk rule means you
don’t risk more than 1% of your capital on a single trade (it's recommended to
avoid the risk of ruin, so you can be wrong several times in a row). There are
two ways traders can apply the 1% (or whichever percentage they choose)
rule. The first is to only use 1% of capital to buy a single asset (Equal Dollar
Method). The second is to use as much capital is needed for a trade, but apply a
stop loss to the position so no more than 1% of the account is lost if the trade
goes the wrong way (*Equal Risk Method*).

** Further Explanation of the 1% Risk Rule:

**The rule is applied so that no single trade causes a massive loss in the
account.**

Day traders and swing traders typically only risk up to 1% of their account on
any single trade, and use the stop loss approach (Equal Risk). For example, a
trader with a $30,000 account can risk up to $300 per trade if risking
1%. Assume they buy a stock at $15, expecting it to go higher, and place a stop
loss (a stop sell order which exits the trade) if the price drops to $14.90. The
trader buys 3000 shares, because if they lose the $0.10 per share ($15 – $14.90)
on 3000 shares, they have only lost $300, or 1% of their account. With a looser
stop loss at 14$, he can buy 300 shares at 15$. In both cases he loses 300$ if
the stop is triggered. The looser the stop the smaller the profit, but
protecting your capital is the number 1 rule. Be aware that a stop loss can be
triggered much lower in case of low liquidity. Gaps are common with stocks,
especially after earnings. If you buy a stock at 15 and put a stop loss at 14.5,
it doesn't mean you will automatically sell it at 14.5. If the next day the
stock drops 50%, your stop will be triggered at the first available bid price at
7.50$.

** Remember:
1. Determine how much of your total capital you're willing to risk per trade
2. Place your stop loss on the chart
3. Determine your position size (the number of shares you can buy):
   https://chartyourtrade.com/position-size-calculator

Trading is hard. Don't trade if you don't have an edge. Deciding when to enter a
trade, where to put a stop loss and when to exit requires skills.

[[https://pastebin.com/sqJUcbjp][link]]
