//@version=4

// TODO: https://kodify.net/tradingview/orders/percentage-profit/
strategy(title="RSI Divergence_alper", shorttitle="RSI Divergence LONG", overlay=true, default_qty_value=0.003, process_orders_on_close=true)
// link: https://in.tradingview.com/script/fH6e5TuN-RSI-Divergence/

src_fast = close, len_fast = input(5, minval=1, title="Length Fast RSI")
src_slow = close, len_slow = input(14,minval=1, title="Length Slow RSI")
//plotfast = plot(rsi_fast, color=blue)
//plotslow = plot(rsi_slow, color=orange)
up_fast = rma(max(change(src_fast), 0), len_fast)
down_fast = rma(-min(change(src_fast), 0), len_fast)
rsi_fast = down_fast == 0 ? 100 : up_fast == 0 ? 0 : 100 - (100 / (1 + up_fast / down_fast))
up_slow = rma(max(change(src_slow), 0), len_slow)
down_slow = rma(-min(change(src_slow), 0), len_slow)
rsi_slow = down_slow == 0 ? 100 : up_slow == 0 ? 0 : 100 - (100 / (1 + up_slow / down_slow))
divergence = rsi_fast - rsi_slow
plotdiv = plot(divergence, color = divergence > 0 ? color.lime:color.red, linewidth = 2)
//band1 = hline(70,color=green)
//band0 = hline(30,color=red)
band = hline(0)

divlong = divergence >=0
divshort = divergence <=0

//
// === INPUT BACKTEST RANGE ===
fromMonth = input(defval = 1,    title = "From Month",      type = input.integer, minval = 1, maxval = 12)
fromDay   = input(defval = 1,    title = "From Day",        type = input.integer, minval = 1, maxval = 31)
fromYear  = input(defval = 2021, title = "From Year",       type = input.integer, minval = 1970)
thruMonth = input(defval = 1,    title = "Thru Month",      type = input.integer, minval = 1, maxval = 12)
thruDay   = input(defval = 1,    title = "Thru Day",        type = input.integer, minval = 1, maxval = 31)
thruYear  = input(defval = 2112, title = "Thru Year",       type = input.integer, minval = 1970)

// === INPUT SHOW PLOT ===
showDate  = input(defval = true, title = "Show Date Range", type = input.bool)

// === FUNCTION EXAMPLE ===
start     = timestamp(fromYear, fromMonth, fromDay, 00, 00)  // backtest start window
finish    = timestamp(thruYear, thruMonth, thruDay, 23, 59)  // backtest finish window
window()  => time >= start and time <= finish ? true : false  // create function "within window of time"
//

// // Make inputs that set the take profit % (optional)
// longProfitPerc = input(title="Long Take Profit (%)",
//      type=input.float, minval=0.0, step=0.1, defval=1) / 100

// shortProfitPerc = input(title="Short Take Profit (%)",
//      type=input.float, minval=0.0, step=0.1, defval=1) / 100

//  // Figure out take profit price
// longExitPrice  = strategy.position_avg_price * (1 + longProfitPerc)
// shortExitPrice = strategy.position_avg_price * (1 - shortProfitPerc)

//tp_inp = input(1.0, title='Take Profit %', type=input.float)/100
//take_level = strategy.position_avg_price * (1 + tp_inp)

strategy.entry("Long", strategy.long, when=window() and divlong) // , limit=take_level
// strategy.entry("Short", strategy.short, when=window() and divshort)

strategy.close("Long", when=window() and divshort)
// bgcolor(color = showDate and window() ? color.gray : na, transp = 90)
data1 = divlong
plotshape(data1, style=shape.triangleup,location=location.bottom, color=color.green , title="DivUp")

data2 = divshort
plotshape(data2, style=shape.triangledown, location=location.top, color=color.red,title="DivDown")
