//@version=4
strategy(title="alper", shorttitle="alper",
     calc_on_order_fills=false, initial_capital=400, default_qty_value=400,
     default_qty_type=strategy.cash, calc_on_every_tick=false, pyramiding=0,
     currency=currency.USD, commission_type=strategy.commission.percent,
     commission_value=0.1)

fromMonth = input(5)
fromDay = input(19)
thruMonth = input(12)
thruDay = input(21)
fromYear = input(2021)
thruYear = input(2021)

// WaveTrend
// =========
n1 = input(10, "Channel Length")
n2 = input(30)

time_frame = "1"
ap = security("BINANCE:DOGEUSDTPERP", time_frame, hlc3)
_close = security("BINANCE:DOGEUSDTPERP", time_frame, close)
src = security("BINANCE:DOGEUSDTPERP", time_frame, ohlc4)
_high = security("BINANCE:DOGEUSDTPERP", time_frame, high)
_low = security("BINANCE:DOGEUSDTPERP", time_frame, low)
_hl2 = security("BINANCE:DOGEUSDTPERP", time_frame, hl2)

// RSI-divergence
src_fast = _close, len_fast = input(5,  minval=1, title="Length Fast RSI") // 5
src_slow = _close, len_slow = input(14, minval=1, title="Length Slow RSI") // 14
// ============================================================================
testPeriodStart = timestamp(fromYear, fromMonth, fromDay, 0, 0)
testPeriodStop  = timestamp(thruYear, thruMonth, thruDay, 0, 0)
start           = timestamp(fromYear, fromMonth, fromDay, 13, 00)
finish          = timestamp(thruYear, thruMonth, thruDay, 23, 59)
window() => time >= start and time <= finish ? true : false

// WaveTrend
// =========
obLevel1 = input(70, "Over Bought Level 1")
obLevel2 = input(53, "Over Bought Level 2")
osLevel1 = input(-70, "Over Sold Level 1")
osLevel2 = input(-53, "Over Sold Level 2")

esa = ema(ap, n1)
d = ema(abs(ap - esa), n1)
ci = (ap - esa) / (0.015 * d)
tci = ema(ci, n2)
wt1 = tci
wt2 = sma(wt1, 4)


plot(obLevel1, color=color.red)
plot(osLevel1, color=color.green)
plot(obLevel2, color=color.red, style=3)
plot(osLevel2, color=color.green, style=3)
plot(wt1, color=color.green)
plot(wt2, color=color.red)
plot(wt1 - wt2, color=color.blue, style=plot.style_area, transp=80)

plot(cross(wt1, wt2) ? wt2 : na, color=color.black , style=plot.style_circles, linewidth=3)
plot(cross(wt1, wt2) ? wt2 : na, color = (wt2 > wt1 ? color.red : color.lime) , style=plot.style_circles, linewidth=2)
barcolor(cross(wt1, wt2) ? (wt2 > wt1 ? color.aqua : color.yellow) : na)

wt1_past_1 = wt1[1]
wt2_past_1 = wt2[1]
divcrosslong  = wt1 < wt2
divcrossshort = wt1 > wt2
_divcrosslong  = divcrosslong and wt1_past_1 > wt2_past_1
_divcrossshort = divcrossshort and wt1_past_1 < wt2_past_1
plot(cross(wt1, wt2) ? wt2 : na, color = (wt2 - wt1 > 0 ? color.red : color.lime) , style=plot.style_circles, linewidth = 2)

// RSI-divergence
up_fast = rma(max(change(src_fast), 0), len_fast)
down_fast = rma(-min(change(src_fast), 0), len_fast)
rsi_fast = down_fast == 0 ? 100 : up_fast == 0 ? 0 : 100 - (100 / (1 + up_fast / down_fast))
up_slow = rma(max(change(src_slow), 0), len_slow)
down_slow = rma(-min(change(src_slow), 0), len_slow)
rsi_slow = down_slow == 0 ? 100 : up_slow == 0 ? 0 : 100 - (100 / (1 + up_slow / down_slow))
divergence = rsi_fast - rsi_slow
band = hline(0)
rsi_divlong = divergence > 0
rsi_divshort = divergence < 0

// if (strategy.position_size == 0 and minute % 5 == 0)
strategy.entry("Long", strategy.long, when=window() and divcrossshort and rsi_divlong)
strategy.entry("Short",strategy.short, when=window() and divcrosslong and rsi_divshort)

// if (minute % 5 == 0 and second < 50 and strategy.position_size != 0)
strategy.close("Long", when=window() and divcrosslong and rsi_divshort)
strategy.close("Short", when=window() and divcrossshort and rsi_divlong)

inpTrailStopL= input(defval = 5000, title = "Trailing Stop Loss", minval = 0)
inpTrailStopS= input(defval = 5000, title = "Trailing Stop Loss", minval = 0)
// strategy.exit("L_TP", from_entry = "Long", trail_points = inpTrailStopL)
// strategy.exit("S_TP", from_entry = "Short", trail_points = inpTrailStopS)

// // {{ticker}},{{strategy.order.action}},{{strategy.market_position}},{{strategy.prev_market_position}},{{timenow}},{{close}}
