//@version=4
strategy(title="alpy", shorttitle="alpy",
     calc_on_order_fills=true, initial_capital=100, default_qty_value=5,
     process_orders_on_close=true,
     default_qty_type=strategy.cash, calc_on_every_tick=true, pyramiding=3,
     currency=currency.USD, commission_type=strategy.commission.percent,
     commission_value=0.1, overlay=true)

fromMonth = input(5)
fromDay = input(23)
thruMonth = input(12)
thruDay = input(30)
fromYear = input(2021)
thruYear = input(2021)
testPeriodStart = timestamp(fromYear, fromMonth, fromDay, 0, 0)
testPeriodStop  = timestamp(thruYear, thruMonth, thruDay, 0, 0)
start           = timestamp(fromYear, fromMonth, fromDay, 13, 00)
finish          = timestamp(thruYear, thruMonth, thruDay, 23, 59)
window() => time >= start and time <= finish ? true : false

//////////////////////////////////////////////////////////////////////////////////
n = input(title="Periods", defval=2, minval=2, type=input.integer)

// UpFractal
bool upflagDownFrontier = true
bool upflagUpFrontier0 = true
bool upflagUpFrontier1 = true
bool upflagUpFrontier2 = true
bool upflagUpFrontier3 = true
bool upflagUpFrontier4 = true

for i = 1 to n
    upflagDownFrontier := upflagDownFrontier and (high[n-i] < high[n])
    upflagUpFrontier0 := upflagUpFrontier0 and (high[n+i] < high[n])
    upflagUpFrontier1 := upflagUpFrontier1 and (high[n+1] <= high[n] and high[n+i + 1] < high[n])
    upflagUpFrontier2 := upflagUpFrontier2 and (high[n+1] <= high[n] and high[n+2] <= high[n] and high[n+i + 2] < high[n])
    upflagUpFrontier3 := upflagUpFrontier3 and (high[n+1] <= high[n] and high[n+2] <= high[n] and high[n+3] <= high[n] and high[n+i + 3] < high[n])
    upflagUpFrontier4 := upflagUpFrontier4 and (high[n+1] <= high[n] and high[n+2] <= high[n] and high[n+3] <= high[n] and high[n+4] <= high[n] and high[n+i + 4] < high[n])
flagUpFrontier = upflagUpFrontier0 or upflagUpFrontier1 or upflagUpFrontier2 or upflagUpFrontier3 or upflagUpFrontier4

upFractal = (upflagDownFrontier and flagUpFrontier)

// downFractal
bool downflagDownFrontier = true
bool downflagUpFrontier0 = true
bool downflagUpFrontier1 = true
bool downflagUpFrontier2 = true
bool downflagUpFrontier3 = true
bool downflagUpFrontier4 = true

for i = 1 to n
    downflagDownFrontier := downflagDownFrontier and (low[n-i] > low[n])
    downflagUpFrontier0 := downflagUpFrontier0 and (low[n+i] > low[n])
    downflagUpFrontier1 := downflagUpFrontier1 and (low[n+1] >= low[n] and low[n+i + 1] > low[n])
    downflagUpFrontier2 := downflagUpFrontier2 and (low[n+1] >= low[n] and low[n+2] >= low[n] and low[n+i + 2] > low[n])
    downflagUpFrontier3 := downflagUpFrontier3 and (low[n+1] >= low[n] and low[n+2] >= low[n] and low[n+3] >= low[n] and low[n+i + 3] > low[n])
    downflagUpFrontier4 := downflagUpFrontier4 and (low[n+1] >= low[n] and low[n+2] >= low[n] and low[n+3] >= low[n] and low[n+4] >= low[n] and low[n+i + 4] > low[n])
flagDownFrontier = downflagUpFrontier0 or downflagUpFrontier1 or downflagUpFrontier2 or downflagUpFrontier3 or downflagUpFrontier4

downFractal = (downflagDownFrontier and flagDownFrontier)
//////////////////////////////////////////////////////////////////////////////////////////////////////////
len = 24
src = security(syminfo.tickerid, "60", hlc3, barmerge.gaps_off, lookahead=barmerge.lookahead_off)
//src = hlc3
ma = vwma(src, len)
plot(ma, title="VWMA", color=color.blue)
upperBandValue = input(3, title = "Short Offset")
lowerBandValue = input(3, title= "Long Offset")
upperBand = plot(ma*(1+upperBandValue/100), title="Upper Band", color=color.red)
lowerBand = plot(ma*(1-lowerBandValue/100), title="Lower Band", color=color.green)

posSize = abs(strategy.position_size)

_value = ma*(1-lowerBandValue/100)

if close < _value and downFractal
    strategy.entry("Long", strategy.long, when=window(), alert_message="enter")

_tp = input(0.05, title = "tp")
if posSize != 0 and  strategy.position_size > 0 and strategy.position_avg_price > close and ((strategy.position_avg_price-close) / close) >= _tp
    strategy.entry("LLong", strategy.long, qty=posSize*2, when=window())

if close >= strategy.position_avg_price * 1.005
    strategy.close_all(when=window())

// inpTrailStop    = input(defval = 5000, title = "Trailing Stop Loss", minval = 0)
// inpTrailOffset  = input(defval = 0, title = "Trailing Stop Loss Offset", minval = 0)å
// strategy.exit("Exit Long", from_entry = "Long", trail_points=inpTrailStop, trail_offset=inpTrailOffset)
// strategy.exit("Exit Short", from_entry = "Short", trail_points = inpTrailStop, trail_offset = inpTrailOffset)

// {{ticker}},{{strategy.order.action}},{{strategy.market_position}},{{strategy.prev_market_position}},{{timenow}},{{strategy.position_size}},{{strategy.order.alert_message}}
