//study(title="W",shorttitle="WT_CROSS")
strategy(title="W",shorttitle="WT_CROSS", initial_capital=1000,currency=currency.USD,default_qty_value=10,default_qty_type=strategy.percent_of_equity)

n1 = input(10, "Channel Length")
n2 = input(21, "Average Length")
obLevel1 = input(60, "Over Bought Level 1")
obLevel2 = input(53, "Over Bought Level 2")
osLevel1 = input(-60, "Over Sold Level 1")
osLevel2 = input(-53, "Over Sold Level 2")

ap = hlc3
esa = ema(ap, n1)
d = ema(abs(ap - esa), n1)
ci = (ap - esa) / (0.015 * d)
tci = ema(ci, n2)

wt1 = tci
wt2 = sma(wt1,4)

plot(0, title="Zero Line")
plot(obLevel1, color=red)
plot(obLevel2, color=red)
plot(osLevel1, color=green)
plot(osLevel2, color=green)

plot(wt1, color=lime)
plot(wt2, color=red)
plot(wt1-wt2, style=area, transp=80, title="Histo")
plot(cross(wt1, wt2) ? wt2 : na, color = black , style = circles, linewidth = 3, title="WT Crossing Outline")
plot(cross(wt1, wt2) ? wt2 : na, color = (wt2 - wt1 > 0 ? red : lime) , style = circles, linewidth = 2, title="WT Crossing Dots")

// Set Alerts for Bull/Bear Cross
wtCross = cross(wt1, wt2)
alertcondition(wtCross, title="Wave Trend Crossing", message="Wave Trend Crossing")

//
fromYear = input(2021, "Backtest Start Year")
fromMonth = input(4, "Backtest Start Month")
fromDay = input(2, "Backtest Start Day")
testPeriodStart = timestamp(fromYear,fromMonth,fromDay,0,0)

thruYear = input(2021, "Backtest Stop Year")
thruMonth = input(12, "Backtest Stop Month")
thruDay = input(30, "Backtest Stop Day")
testPeriodStop = timestamp(thruYear,thruMonth,thruDay,0,0)

start     = timestamp(fromYear, fromMonth, fromDay, 00, 00)  // backtest start window
finish    = timestamp(thruYear, thruMonth, thruDay, 23, 59)  // backtest finish window
window()  => time >= start and time <= finish ? true : false

divcrossshort = wt1 - wt2 < 0
divcrosslong = wt1 - wt2 > 0

//alertcondition(divcrosslong, title='DOGE,LONG,OPEN', message='Div Long')
//alertcondition(divcrossshort, title='DOGE,LONG,CLOSE', message='Div Long')
//
//alertcondition(divcrossshort, title='DOGE,SHORT,OPEN', message='Div Long')
//alertcondition(divcrosslong, title='DOGE,SHORT,CLOSE', message='Div Long')

strategy.entry("Long", strategy.long, when=window() and divcrosslong)
strategy.close("Long", when=window() and divcrossshort)

strategy.entry("Short",strategy.short, when=window() and divcrossshort)
strategy.close("Short", when=window() and divcrosslong)
