//@version=4
//strategy(title="uabmeacd", shorttitle="uabmacd", overlay=false, initial_capital=1000, calc_on_every_tick=false, pyramiding=0, currency=currency.USD, default_qty_type=strategy.percent_of_equity, default_qty_value=20, commission_type=strategy.commission.percent, commission_value=0.01)
study(title="uabmacd",shorttitle="uabmacd")

fromYear = input(2021, "Backtest Start Year")
fromMonth = input(5, "Backtest Start Month")
fromDay = input(17, "Backtest Start Day")

thruYear = input(2021, "Backtest Stop Year")
thruMonth = input(12, "Backtest Stop Month")
thruDay = input(30, "Backtest Stop Day")

// WaveTrend
// =========
n1 = input(10, "Channel Length")
n2 = input(21, "Average Length")
obLevel1 = input(60, "Over Bought Level 1")
obLevel2 = input(53, "Over Bought Level 2")
osLevel1 = input(-60, "Over Sold Level 1")
osLevel2 = input(-53, "Over Sold Level 2")

ap = hlc3
esa = ema(ap, n1)
d = ema(abs(ap - esa), n1)
ci = (ap - esa) / (0.015 * d)
tci = ema(ci, n2)

wt1 = tci
wt2 = sma(wt1,4)

//plot(0, color=gray)
plot(obLevel1, color=color.red)
plot(osLevel1, color=color.green)
plot(obLevel2, color=color.red, style=3)
plot(osLevel2, color=color.green, style=3)
plot(wt1, color=color.green)
plot(wt2, color=color.red)
plot(wt1-wt2, color=color.blue, style=plot.style_area, transp=80)

plot(cross(wt1, wt2) ? wt2 : na, color=color.black , style=plot.style_circles, linewidth = 3)
plot(cross(wt1, wt2) ? wt2 : na, color = (wt2 > wt1 ? color.red : color.lime) , style=plot.style_circles, linewidth = 2)
barcolor(cross(wt1, wt2) ? (wt2 - wt1 > 0 ? color.aqua : color.yellow) : na)

wt1_past_1 = wt1[1]
wt2_past_1 = wt2[1]

divcrosslong  = wt1 < wt2
divcrossshort = wt1 > wt2

_divcrosslong  = divcrosslong and wt1_past_1 > wt2_past_1
_divcrossshort = divcrossshort and wt1_past_1 < wt2_past_1

// _divlong = _divcrossshort and wt1_past_1 < osLevel2
// _divshort = _divcrosslong and wt1_past_1 > obLevel2
// data1 = divlong
// data2 = divshort
// plotshape(data1, style=shape.xcross,location=location.bottom, color=green, size = size.tiny, title="WT_up")
// plotshape(data2, style=shape.xcross,location=location.top, color=red, size = size.tiny, title="WT_down")
// plotshape(data1 or data2, style=shape.xcross,location=location.absolute, color=gray, title="WT_BOTH")
plot(cross(wt1, wt2) ? wt2 : na, color = color.black, style=plot.style_circles, linewidth = 3)
plot(cross(wt1, wt2) ? wt2 : na, color = (wt2 - wt1 > 0 ? color.red : color.lime) , style=plot.style_circles, linewidth = 2)

testPeriodStart = timestamp(fromYear,fromMonth,fromDay,0,0)
testPeriodStop = timestamp(thruYear,thruMonth,thruDay,0,0)

start     = timestamp(fromYear, fromMonth, fromDay, 00, 00)  // backtest start window
finish    = timestamp(thruYear, thruMonth, thruDay, 23, 59)  // backtest finish window
window()  => time >= start and time <= finish ? true : false

// alertcondition(_divcrossshort, title='LONG,EVERY_MIN',  message='DOGEUSDT,LONG,MIN,price={{close}}, volume={{volume}}')
// alertcondition(_divcrosslong,  title='SHORT,EVERY_MIN', message='DOGEUSDT,SHORT,MIN,price={{close}},volume={{volume}}')

// alertcondition(divcrossshort, title='LONG,BAR_CLOSE',  message='DOGEUSDT,LONG,BAR_CLOSE,***,price={{close}}, volume={{volume}}')
// alertcondition(divcrosslong, title='SHORT,BAR_CLOSE', message='DOGEUSDT,SHORT,BAR_CLOSE,***,price={{close}}, volume={{volume}}')

//longProfitPerc = input(title="Long Take Profit (%)", type=input.float, minval=0.0, step=0.1, defval=8) * 0.01
//shortProfitPerc = input(title="Short Take Profit (%)", type=input.float, minval=0.0, step=0.1, defval=8) * 0.01
//longExitPrice  = strategy.position_avg_price * (1 + longProfitPerc)
//shortExitPrice = strategy.position_avg_price * (1 - shortProfitPerc)

// Plot take profit values for confirmation
//plot(series=(strategy.position_size > 0) ? longExitPrice : na,
//     color=color.green, style=plot.style_circles,
//     linewidth=3, title="Long Take Profit")
//plot(series=(strategy.position_size < 0) ? shortExitPrice : na,
//     color=color.red, style=plot.style_circles,
//     linewidth=3, title="Short Take Profit")

//-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-

//if (strategy.position_size > 0)
//    strategy.exit(id="XL TP", limit=longExitPrice)

//if (strategy.position_size < 0)
//    strategy.exit(id="XS TP", limit=shortExitPrice)
//-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-

// Squeeze Momentum Strategy
// =========================
length = input(12, title="BB Length")
mult = input(2.0, title="BB MultFactor")
lengthKC = input(16, title="KC Length")
mult_kc = input(1.5, title="KC MultFactor")


//FILTERS
useMomAverage = input(false, title="Filter for Momenutum value", type=input.bool)
MomentumMin = input(20, title="Min for momentum")

// Calculate BB
src = ohlc4

ma_1 = sma(src, length)
ma_2 = sma(src, lengthKC)
range_ma = sma(high - low, lengthKC)

dev = mult * stdev(src, length)

upper_bb = ma_1 + dev
lower_bb = ma_1 - dev

upper_kc = ma_2 + range_ma * mult_kc
lower_kc = ma_2 - range_ma * mult_kc

sqz_on = lower_bb > lower_kc and upper_bb < upper_kc
sqz_off = lower_bb < lower_kc and upper_bb > upper_kc
no_sqz = sqz_on == false and sqz_off == false

val = linreg(src - avg(avg(highest(hl2, lengthKC), lowest(low, lengthKC)), sma(hl2, lengthKC)), lengthKC, 0)

bcolor = iff(val > 0, iff(val > nz(val[1]), color.lime, color.green), iff(val < nz(val[1]), color.red, color.maroon))
scolor = no_sqz ? color.blue : sqz_on ? color.black : color.aqua
plot(val, color=bcolor, style=plot.style_histogram, linewidth=4)
plot(0, color=scolor, style=plot.style_cross, linewidth=2)

//LOGIC
//momentum filter
filterMom = useMomAverage ? abs(val) > MomentumMin / 100000 ? true : false : true

//standard condition
longCondition = scolor[1] != color.aqua and scolor == color.aqua and bcolor == color.lime and filterMom
exitLongCondition = bcolor == color.green
shortCondition = scolor[1] != color.aqua and scolor == color.aqua and bcolor == color.red and filterMom
exitShortCondition = bcolor == color.maroon

// Risk Management Sysyem
stop_loss = input(defval = 600, title="Stop Loss", minval = 0)
take_profit = input(defval = 1000, title="Take Profit", minval = 0)
trailing_stop = input(defval = 20, title="Trailing Stop", minval = 0)
// If the zero value is set for stop loss, take profit or trailing stop, then the function is disabled
s_loss = stop_loss >= 1 ? stop_loss : na
tk_profit = take_profit >= 1 ? take_profit : na
tr_stop = trailing_stop >= 1 ? trailing_stop : na

// =================================================================================================================
alertcondition(_divcrossshort, title='LONG,BAR_CROSS',  message='DOGEUSDT,LONG,BAR_CROSS,price={{close}}, volume={{volume}}')
alertcondition(_divcrosslong and sqz_off,  title='SHORT,CLOSE_POS', message='DOGEUSDT,SHORT,CLOSE_POS,price={{close}},volume={{volume}}')
//
alertcondition(_divcrosslong and sqz_on,  title='SHORT,BAR_CROSS', message='DOGEUSDT,SHORT,BAR_CROSS,price={{close}},volume={{volume}}')
// alertcondition(_divcrosslong and sqz_on,  title='SHORT,BAR_CROSS_SQ', message='DOGEUSDT,SHORT,BAR_CROSS_SQ,price={{close}},volume={{volume}}')
// =================================================================================================================
//strategy.entry("Long", strategy.long, when=window() and _divcrossshort)
//strategy.close("Long", when=window() and _divcrosslong)
//strategy.entry("Short",strategy.short, when=window() and _divcrosslong and sqz_on)
//strategy.close("Short", when=window() and _divcrossshort)
