//@version=4
strategy(title="{{ticker}},{{strategy.order.action}},{{strategy.order.alert_message}},{{close}},",
     shorttitle="alpy_vix", calc_on_order_fills=true, process_orders_on_close=true,
     default_qty_type=strategy.cash, calc_on_every_tick=true, pyramiding=100000,
     overlay=false)
fromMonth = 2
fromDay   = 1
thruMonth = 1
thruDay   = 1
fromYear  = 2022
thruYear  = 3000
testPeriodStart = timestamp(fromYear, fromMonth, fromDay, 0, 0)
testPeriodStop  = timestamp(thruYear, thruMonth, thruDay, 0, 0)
start           = timestamp(fromYear, fromMonth, fromDay, 13, 00)
finish          = timestamp(thruYear, thruMonth, thruDay, 23, 59)
window() => time >= start and time <= finish ? true : false
msg = timeframe.period + "_enter"
// hunter
vwap_period = input(title="Period", defval=5)
vwap_source = hlc3
vwap_price_volume = vwap_source * volume
sum_vwap_source = sum(vwap_price_volume, vwap_period)
sumVolume = sum(volume, vwap_period)
vwap_value = sum_vwap_source / sumVolume
vwap_above = 0.0
_vwap_above = 0.0
if close > 0.001
    vwap_above  := vwap_value * (1 + (0.75 / 100))
    _vwap_above := vwap_value * (1 + (1.20 / 100))
else
    vwap_above  := vwap_value * (1 + (0.80 / 100))
    _vwap_above := vwap_value * (1 + (1.20 / 100))

long_VWMA = vwap_above <= close and close < _vwap_above
// cm_williams vix fix formula
pd = input(22, title="lookback period standard deviation high")
bbl = input(20, title="bolinger band length")
mult = input(2.0 , minval=1, maxval=5, title="Bollinger Band Standard Devaition Up")
lb = input(50, title="look back period percentile high")
ph = input(.85, title="Highest Percentile - 0.90=90%, 0.95=95%, 0.99=99%")
sbc = input(false, title="show Highlight Bar if WVF WAS True and IS Now False")
sbcc = input(false, title="show Highlight Bar if WVF IS True")
new2 = input(false, title="Highlight Bars Below Use FILTERED Criteria" )
new3 = input(false, title="Check Below to turn All Bars Gray, Then Check the Boxes Above, And your will have Same Colors As VixFix")
sgb = input(false, title="Check Box To Turn Bars Gray?")
// Criteria for Down Trend Definition for Filtered Pivots and Aggressive Filtered Pivots
ltLB = input(40, minval=25, maxval=99, title="Long-Term Look Back Current Bar Has To Close Below This Value OR Medium Term--Default=40")
mtLB = input(14, minval=10, maxval=20, title="Medium-Term Look Back Current Bar Has To Close Below This Value OR Long Term--Default=14")
str = input(3, minval=1, maxval=9, title="Entry Price Action Strength--Close > X Bars Back---Default=3")
swvf = input(true, title="show Williams Vix Fix Histogram, Uncheck to Turn Off!")
sa1 = input(false, title="show Alert WVF = True?")
sa2 = input(false, title="show Alert WVF Was True Now False?")
sa3 = input(false, title="show Alert WVF Filtered?")
sa4 = input(true, title="show alert WVF AGGRESSIVE Filter?")
// williams vix fix formula
wvf = ((highest(close, pd)-low)/(highest(close, pd)))*100
sDev = mult * stdev(wvf, bbl)
midLine = sma(wvf, bbl)
upper_band = midLine + sDev
rangeHigh = (highest(wvf, lb)) * ph
// filtered bar criteria
upRange = low > low[1] and close > high[1]
upRange_aggr = close > close[1] and close > open[1]
// filtered criteria
filtered = ((wvf[1] >= upper_band[1] or wvf[1] >= rangeHigh[1]) and (wvf < upper_band and wvf < rangeHigh))
filtered_aggr = (wvf[1] >= upper_band[1] or wvf[1] >= rangeHigh[1]) and not (wvf < upper_band and wvf < rangeHigh)
// alerts criteria
alert1 = wvf >= upper_band or wvf >= rangeHigh ? 1 : 0
alert2 = (wvf[1] >= upper_band[1] or wvf[1] >= rangeHigh[1]) and (wvf < upper_band and wvf < rangeHigh) ? 1 : 0
alert3 = upRange and close > close[str] and (close < close[ltLB] or close < close[mtLB]) and filtered ? 1 : 0
alert4 = upRange_aggr and close > close[str] and (close < close[ltLB] or close < close[mtLB]) and filtered_aggr ? 1 : 0
// highlight bar criteria
barcolor(alert3 ? color.fuchsia : na)
barcolor(alert4 ? color.orange  : na)
barcolor(sbc and ((wvf[1] >= upper_band[1] or wvf[1] >= rangeHigh[1]) and (wvf < upper_band and wvf < rangeHigh)) ? color.aqua : na)
barcolor(sbcc and (wvf >= upper_band or wvf >= rangeHigh) ? color.lime : na)
barcolor(sgb and close ? color.gray : na)
// coloring criteria of williams vix fix
col = wvf >= upper_band or wvf >= rangeHigh ? color.lime : color.gray
col_fuchsia = alert3 ? color.fuchsia : na
col_aggressive = alert4 ? color.orange : color.red
// plots for williams vix fix histogram and alerts
plot(swvf and wvf ? wvf * -1 : na, title="Williams Vix Fix", style=plot.style_columns, linewidth = 4, color=col)
plot(sa1 and alert1 ? alert1 : 0, title="alert If WVF = True", style=plot.style_columns, linewidth=2, color=color.lime)
plot(sa2 and alert2 ? alert2 : 0, title="alert If WVF Was True Now False", style=plot.style_columns, linewidth=2, color=color.aqua)
plot(sa3 and alert3 ? alert3 : 0, title="alert Filtered Entry", style=plot.style_columns, linewidth=2, color=color.fuchsia)
plot(sa4 and alert4 ? alert4 : 0, title="alert Aggressive Filtered Entry", style=plot.style_columns, linewidth=2, color=color.orange)
// ************
// Buy Alerts *
// ************
if close < vwap_value * (1 + (0.8/100))
    msg := msg + "_0.75"
else if close < vwap_value * (1 + (0.9/100))
    msg:= msg + "_0.8"
else if close < vwap_value * (1 + (1.0/100))
    msg:= msg + "_0.9"
else if close < vwap_value * (1 + (1.1/100))
    msg := msg + "_1.0"
else if close < vwap_value * (1 + (1.2/100))
    msg := msg + "_1.1"

if strategy.position_size[0] != 0  // close position for alpy-bot new incoming alerts
    if bar_index > abs(strategy.position_size) + 10
        strategy.close_all(when=window())

buy_signal  = (col[1] == color.lime and col == color.gray) and long_VWMA  // and close > close[100]
if buy_signal
    if strategy.opentrades[0] == 0 or strategy.position_size < 0
        strategy.entry("Long", strategy.long, qty=bar_index, when=window(), alert_message=msg)
    else
        if bar_index > abs(strategy.position_size)
            if strategy.position_size[0] != 0
                strategy.close_all(when=window())
            else
                strategy.entry("Long", strategy.long, qty=bar_index, when=window(), alert_message=msg)
