//@version=5
strategy(title='{{ticker}},{{strategy.order.action}},{{strategy.order.alert_message}},{{close}},', shorttitle='alpy_vix', calc_on_order_fills=true, process_orders_on_close=true, default_qty_type=strategy.cash, calc_on_every_tick=true, pyramiding=100000, overlay=false)
fromMonth = 3
fromDay = 1
thruMonth = 1
thruDay = 1
fromYear = 2022
thruYear = 3000
testPeriodStart = timestamp(fromYear, fromMonth, fromDay, 0, 0)
testPeriodStop = timestamp(thruYear, thruMonth, thruDay, 0, 0)
start = timestamp(fromYear, fromMonth, fromDay, 13, 00)
finish = timestamp(thruYear, thruMonth, thruDay, 23, 59)
msg = timeframe.period + '_enter'
msg_aggr = msg + '_aggr'
window() =>
    time >= start and time <= finish ? true : false

// hunter
vwap_period = input(title='Period', defval=5)
vwap_source = hlc3
vwap_price_volume = vwap_source * volume
sum_vwap_source = math.sum(vwap_price_volume, vwap_period)
sumVolume = math.sum(volume, vwap_period)
vwap_value = sum_vwap_source / sumVolume
vwap_above = 0.0
vwap_above_limit = 0.0
vwap_above := vwap_value * (1 + 0.65 / 100)
vwap_above_limit := vwap_value * (1 + 1.20 / 100)
long_VWMA = vwap_above <= close and close < vwap_above_limit

// cm_williams vix fix formula
pd = input(22, title='lookback period standard deviation high')
bbl = input(20, title='bolinger band length')
mult = input.float(2.0, minval=1, maxval=5, title='Bollinger Band Standard Devaition Up')
lb = input(50, title='look back period percentile high')
ph = input(.85, title='highest percentile - 0.90=90%, 0.95=95%, 0.99=99%')
sbc = input(false, title='show Highlight Bar if WVF WAS True and IS Now False')
sbcc = input(false, title='show highlight bar if WVF is True')
sgb = input(false, title='check box to turn bars gray?')
// Criteria for Down Trend Definition for Filtered Pivots and Aggressive Filtered Pivots
ltLB = input.int(40, minval=25, maxval=99, title='long-term look back current bar has to close below this value OR Medium Term--Default=40')
mtLB = input.int(14, minval=10, maxval=20, title='Medium-Term Look Back Current Bar Has To Close Below This Value OR Long Term--Default=14')
str = input.int(3, minval=1, maxval=9, title='Entry Price Action Strength--Close > X Bars Back---Default=3')
sa1 = input(false, title='show alert WVF = True?')
sa2 = input(false, title='show alert WVF Was True Now False?')
sa3 = input(false, title='show alert WVF Filtered?')

// williams vix fix formula
wvf = (ta.highest(close, pd) - low) / ta.highest(close, pd) * 100
sDev = mult * ta.stdev(wvf, bbl)
midLine = ta.sma(wvf, bbl)
upper_band = midLine + sDev
rangeHigh = ta.highest(wvf, lb) * ph
// filtered bar criteria
upRange = low > low[1] and close > high[1]
upRange_aggr = close > close[1] and close > open[1]
// filtered criteria
filtered = (wvf[1] >= upper_band[1] or wvf[1] >= rangeHigh[1]) and wvf < upper_band and wvf < rangeHigh
filtered_aggr = (wvf[1] >= upper_band[1] or wvf[1] >= rangeHigh[1]) and not(wvf < upper_band and wvf < rangeHigh)
// alerts criteria
alert1 = wvf >= upper_band or wvf >= rangeHigh ? 1 : 0
alert2 = (wvf[1] >= upper_band[1] or wvf[1] >= rangeHigh[1]) and wvf < upper_band and wvf < rangeHigh ? 1 : 0
alert3 = upRange and close > close[str] and (close < close[ltLB] or close < close[mtLB]) and filtered ? 1 : 0
alert4 = upRange_aggr and close > close[str] and (close < close[ltLB] or close < close[mtLB]) and filtered_aggr ? 1 : 0
// highlight bar criteria
barcolor(alert3 ? color.fuchsia : na)
barcolor(alert4 ? color.orange : na)
barcolor(sbc and (wvf[1] >= upper_band[1] or wvf[1] >= rangeHigh[1]) and wvf < upper_band and wvf < rangeHigh ? color.aqua : na)
barcolor(sbcc and (wvf >= upper_band or wvf >= rangeHigh) ? color.lime : na)
barcolor(sgb and close ? color.gray : na)
// coloring criteria of williams vix fix
col = wvf >= upper_band or wvf >= rangeHigh ? color.lime : color.gray
col_fuchsia = alert3 ? color.fuchsia : na
col_aggressive = alert4 ? color.orange : color.red
// plots for williams vix fix histogram and alerts
plot(wvf ? wvf * -1 : na, title='williams vix fix', style=plot.style_columns, linewidth=4, color=col)
plot(sa1 and alert1 ? alert1 : 0, title='alert If WVF = True', style=plot.style_columns, linewidth=2, color=color.new(color.lime, 0))
plot(sa2 and alert2 ? alert2 : 0, title='alert If WVF Was True Now False', style=plot.style_columns, linewidth=2, color=color.new(color.aqua, 0))
plot(sa3 and alert3 ? alert3 : 0, title='alert Filtered Entry', style=plot.style_columns, linewidth=2, color=color.new(color.fuchsia, 0))
plot(alert4 ? alert4 : 0, title='alert aggressive filtered entry', style=plot.style_columns, linewidth=2, color=color.new(color.orange, 0))

// buy alerts
// ==========
if close < vwap_value * (1 + 0.71 / 100)
    msg += '_0.70'
else if close < vwap_value * (1 + 0.72 / 100)
    msg += '_0.71'
else if close < vwap_value * (1 + 0.73 / 100)
    msg += '_0.72'
else if close < vwap_value * (1 + 0.74 / 100)
    msg += '_0.73'
else if close < vwap_value * (1 + 0.75 / 100)
    msg += '_0.74'
else if close < vwap_value * (1 + 0.76 / 100)
    msg += '_0.75'
else if close < vwap_value * (1 + 0.77 / 100)
    msg += '_0.76'
else if close < vwap_value * (1 + 0.78 / 100)
    msg += '_0.77'
else if close < vwap_value * (1 + 0.79 / 100)
    msg += '_0.78'
else if close < vwap_value * (1 + 0.8 / 100)
    msg += '_0.79'
else if close < vwap_value * (1 + 0.9 / 100)
    msg += '_0.8'
else if close < vwap_value * (1 + 1.0 / 100)
    msg += '_0.9'
else if close < vwap_value * (1 + 1.1 / 100)
    msg += '_1.0'
else if close < vwap_value * (1 + 1.2 / 100)
    msg += '_1.1'

dailyPerChange = (close - close[86400]) / close[86400] * 100

//: try 600 (10 minutes? instead 15 seconds)
// close position for alpy-bot new incoming alerts
// wait for 10 minutes for the next alert, gain might be less due to less
// alerts will show up but risk will be lower. Rapid alerts won't show up.
SLEEP_BAR = 0
if timeframe.isseconds
    SLEEP_BAR := 20
else
    SLEEP_BAR := 1

if strategy.position_size[0] != 0 and bar_index > math.abs(strategy.position_size) + SLEEP_BAR
    strategy.close_all(when=window())

buy_flag = false
if timeframe.isseconds
    if (col[1] == color.gray and col == color.lime or col[1] == color.lime and col == color.gray) and long_VWMA
        buy_flag := true
else
    if col_aggressive == color.orange
        msg := msg_aggr

    // if (col_aggressive == color.orange or (col[1] == color.lime and col == color.gray)) and long_VWMA
    if (col_aggressive == color.orange or col[1] == color.gray and col == color.lime) and long_VWMA
        buy_flag := true

if buy_flag
    if strategy.opentrades[0] == 0 or strategy.position_size < 0
        strategy.entry('long', strategy.long, qty=bar_index, when=window(), alert_message=msg)
    else if bar_index > math.abs(strategy.position_size)
        if strategy.position_size[0] != 0
            strategy.close_all(when=window())
        else
            strategy.entry('long', strategy.long, qty=bar_index, when=window(), alert_message=msg)
